### ISSUE TITLE
How to run with python3.5?

### ISSUE THREAD

**Issue by imistyrain** [OValery16/gender-age-classification#8]
Your code is tested with pyhton2.7 and the model was saved with 2.7, but when tried to run it with python3.5, I got his error:
Traceback (most recent call last):
  File "d:\Program Files\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 230, in func_load
    raw_code = codecs.decode(code.encode('ascii'), 'base64')
UnicodeEncodeError: 'ascii' codec can't encode character '\x83' in position 37: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Face\FaceAttribute\gender-age-classification-master\demo.py", line 21, in <module>
    loaded_model = model_from_json(loaded_model_json, custom_objects={"tf": tf})
  File "d:\Program Files\Anaconda3\lib\site-packages\keras\engine\saving.py", line 368, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "d:\Program Files\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "d:\Program Files\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "d:\Program Files\Anaconda3\lib\site-packages\keras\engine\network.py", line 1017, in from_config
    process_layer(layer_data)
  File "d:\Program Files\Anaconda3\lib\site-packages\keras\engine\network.py", line 1003, in process_layer
    custom_objects=custom_objects)
  File "d:\Program Files\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "d:\Program Files\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "d:\Program Files\Anaconda3\lib\site-packages\keras\engine\network.py", line 1017, in from_config
    process_layer(layer_data)
  File "d:\Program Files\Anaconda3\lib\site-packages\keras\engine\network.py", line 1003, in process_layer
    custom_objects=custom_objects)
  File "d:\Program Files\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "d:\Program Files\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "d:\Program Files\Anaconda3\lib\site-packages\keras\layers\core.py", line 730, in from_config
    function = func_load(config['function'], globs=globs)
  File "d:\Program Files\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 235, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)

**Comment by OValery16** [comment]
check that:

https://github.com/keras-team/keras/issues/8738

If you like you like this project, feel free to leave a star. (it is my only reward ^^)

**Comment by imistyrain** [comment]
That's not the same problem.
After validate it's performance, I will star this project.
